spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 8e9a1956a6caaa646b99
            clientSecret: effc01e8f75998c1f8ba8fae950f704f10ffe309
          google:
            client-id: google-client-id
            client-secret: google-client-secret
# ...